name: Run API Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run API Tests
        run: pytest api_tests/conftest.py --html=report.html --self-contained-html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: report.html
